### PR TITLE
FIX: don't keep overwriting the data in the config file.

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @arkilic @licode

**Review by tacaswell — APPROVED** [review]

**Comment by licode** [comment]
Thanks for fixing the bugs, @CJ-Wright .

**Comment by CJ-Wright** [comment]
Sure, the effect me too.

**Comment by CJ-Wright** [comment]
Related, can anyone let me know what is wrong here? I am using the nsls-ii ci scripts
https://travis-ci.org/CJ-Wright/xpdAn/jobs/160895254

**Comment by licode** [comment]
I think that is related to the latest update at metadatastore https://github.com/NSLS-II/metadatastore/pull/248. We need to add mongo user to config file. We will change this script later.
Or you can use old version of metadatastore=0.6.0.

**Comment by CJ-Wright** [comment]
The script has both a user and password.

**Comment by CJ-Wright** [comment]
Never mind the error was on my end.

**Pull request merged**
